version: "3.8"

services:
  plainsofpain:
    image: ghcr.io/traxo-xx/plainsofpain-server:latest
    container_name: plainsofpain
    hostname: plainsofpain
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15637:15637/udp"
    volumes:
      - ./game:/opt/plainsofpain
      - ./worldfiles:/home/plainsofpain/.config/unity3d/CobraByteDigital/PlainsOfPain
    environment:
      - SERVER_NAME=PlainsOfPainTest
      - SERVER_SEED=
      - SERVER_WORLD_ID=
      - SERVER_DIFFICULTY=
      - SERVER_MAP_ID=
      - SERVER_WORLD_SIZE=
      - SERVER_SLOT_COUNT=10
      - PUID=4711
      - PGID=4711
      - UPDATE_CRON=*/30 * * * *
      - log_level=50
