services:
  starbound:
    image: ghcr.io/knaledge/openstarbound-server:latest
    container_name: starbound-server
    hostname: starbound
    restart: unless-stopped
    stop_grace_period: 2m
    cap_add:
      - sys_nice
    ports:
      - "21025:21025/tcp"
      - "21025:21025/udp"
    volumes:
      - /path/to/volume:/opt/starbound
    secrets:
      - steam_username
      - steam_password      
    environment:
      - PUID=4711
      - PGID=4711
      - UPDATE_CRON=*/30 * * * *
      - log_level=50      
      # - SERVER_NAME=PlainsOfPainTest
      # - SERVER_SEED=40377
      # - SERVER_WORLD_ID=0
      # - SERVER_DIFFICULTY=2
      # - SERVER_MAP_ID=0
      # - SERVER_WORLD_SIZE=5
      # - SERVER_SLOT_COUNT=10

secrets:
  steam_username:
    file: /path/to/secrets/steam_username.txt
  steam_password:
    file: /path/to/secrets/steam_password.txt      