services:
  starbound:
    image: ghcr.io/knaledge/openstarbound-server:latest
    container_name: starbound-server
    hostname: starbound
    restart: unless-stopped
    stop_grace_period: 2m
    cap_add:
      - sys_nice
    ports:
      - "21025:21025/tcp"
      - "21026:21026/tcp"
    volumes:
      - /path/to/volume:/opt/starbound
    secrets:
      - steam_username
      - steam_password
      - starbound_rcon_password
    environment:
      - PUID=4711
      - PGID=4711
      - UPDATE_CRON=0 3 * * 0
      - log_level=50
      - SERVER_NAME="Starbound Server"
      - SERVER_RCON_ENABLED=false

secrets:
  steam_username:
    file: /path/to/secrets/volume/steam_username.txt
  steam_password:
    file: /path/to/secrets/volume/steam_password.txt
  rcon_password:
    file: /path/to/secrets/volume/starbound_rcon_password.txt