services:
  starbound:
    tty: true
    stdin_open: true
    image: ghcr.io/knaledge/openstarbound-server:latest
    container_name: starbound-server
    hostname: starbound
    restart: unless-stopped
    stop_grace_period: 2m
    cap_add:
      - sys_nice
    ports:
      - "21025:21025/tcp"                # Match with 'SERVER_PORT' value
      - "21026:21026/tcp"                # Match with 'SERVER_RCON_PORT' value
    volumes:
      - /path/to/volume/for/game-data:/opt/starbound
      - /path/to/volume/for/steam-data:/home/starbound/Steam
    secrets:
      - steam_username
      - steam_password
      - starbound_rcon_password
    environment:
      - PUID=4711                        # Docker Process User ID; default is "4711"
      - PGID=4711                        # Docker Process Group ID; default is "4711"
      - UPDATE_CRON=0 3 * * 0            # Default is update every Sunday at 3 AM (server host time)
      - BACKUP_CRON=0 4 * * *            # Default is backup every day at 4 AM (server host time)
      - BACKUP_MAX_COUNT=7               # Default is retain a max of 7 backups before overwriting the oldest
      - log_level=50                     # Default is "50" (debug); 0-100 (0=none, 100=all)  
      - SERVER_NAME=Starbound Server
      - SERVER_PORT=21025                # Match with 'ports' definition; default is "21025"
      - SERVER_RCON_PORT=21026           # Match with 'ports' definition; default is "21026"
      - SERVER_RCON_ENABLED=false        # Forced to "false" if 'starbound_rcon_password' secret is undefined
      - SERVER_SLOT_COUNT=8
      - SERVER_CHECK_ASSETS=false        # Forced to "true" when 'USE_OPENSTARBOUND' is "true"
      - USE_OPENSTARBOUND=false          # Enable deployment of OpenStarbound on top of the Starbound game server

secrets:
  steam_username:
    file: /path/to/secrets/volume/steam_username.txt
  steam_password:
    file: /path/to/secrets/volume/steam_password.txt
  starbound_rcon_password:
    file: /path/to/secrets/volume/starbound_rcon_password.txt