name: Bug Report
description: Report a bug to give it a chance of being addressed
labels: [ "bug" ]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing GitHub issue for this?
      description: Please search existing GitHub issues to avoid creating duplicates
      options:
        - label: I have searched the existing GitHub issues
          required: true

  - type: input
    attributes:
      label: Container image version
      description: Which version of the container image is currently being used? Consider providing the SHA256 of the container image
    validations:
      required: true

  - type: textarea
    attributes:
      label: Docker Compose / Docker command-line
      description: Please remove any sensitive information
    validations:
      required: false

  - type: textarea
    attributes:
      label: What did you notice/experience? What did you expect instead?
      description: Please provide a clear and concise description of the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Container log
      description: If possible, please include logs from the container (from `docker compose logs` or `docker logs`)
    validations:
      required: false
