name: Questions
description: Ask a question about the project
labels: [ "question" ]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing GitHub issue for this?
      description: Please search existing GitHub issues to avoid creating duplicates
      options:
        - label: I have searched the existing GitHub issues
          required: true

  - type: textarea
    attributes:
      label: Question
      description: Please ask a clear and concise question
    validations:
      required: true
