#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/bootstrap-validator"

main() {
  validateEnvironmentVariables
  createFolders
  applyPermissions
  setupSyslog
  setupModlist
  steamGuardAuth # Allows for Steam Guard code entry in a pre-Supervisor interactive shell; traversed if 'STEAMGUARD_REQUIRED' is set to "true"
    exit_code=$?

    if [ "$exit_code" -eq 42 ]; then
      error "SteamCMD authentication failed or timed out - terminating deployment and stopping container"
      exit 0  # exit cleanly so that the container 'restart' policy does not count it as a "failure"; stops the container
    elif [ "$exit_code" -ne 0 ]; then
      error "Unexpected error during 'bootstrap' routine (exit code: $exit_code) - restarting container..."
      exit $exit_code  # defer to the container restart policy for all other failures/exit codes
    fi

  exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
}

createFolders() {
  info "Creating server folders (save, logs, backup)"

  if [[ -n "$BACKUP_CRON" ]] && [[ -n "$BACKUP_DIR" ]]; then
    if [[ "$BACKUP_DIR" == /* ]]; then
      mkdir -p "$BACKUP_DIR"
    else
      mkdir -p "$install_path/$BACKUP_DIR"
    fi
  fi
}

# Apply user id and group id
applyPermissions() {
  info "Setting uid:gid of starbound to $PUID:$PGID"
  groupmod -g "${PGID}" -o starbound
  usermod -u "${PUID}" -o starbound
  sed -i -E "s/^(starbound:x):[0-9]+:[0-9]+:(.*)/\\1:$PUID:$PGID:\\2/" /etc/passwd

  chown -R starbound:starbound \
    /opt/starbound \
    /home/starbound \
    /var/run/starbound

  if [[ "$BACKUP_DIR" == /* ]]; then
    debug "Setting permissions for $BACKUP_DIR"
    chown -R starbound:starbound "$BACKUP_DIR"
  fi

  chgrp starbound /etc/supervisor/supervisord.conf
}

# Configure syslog
setupSyslog() {
  info "Setting up syslogd - logging to stdout"

  cat >"$rsyslog_conf" <<EOF
\$FileOwner root
\$FileGroup root
\$PrivDropToUser root
\$PrivDropToGroup root

\$template custom,"%timegenerated:1:10:date-rfc3339% %timegenerated:12:23:date-rfc3339% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
\$ActionFileDefaultTemplate custom

:msg, contains, "[session] Pending packets list is full" ~
*.*;cron,auth,authpriv.none /proc/self/fd/1          # send everything to stdout
EOF

  cat >"$supervisor_syslog_conf" <<EOF
[program:rsyslogd]
user=root
environment=HOME="/root",USER="root",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/sbin/rsyslogd -n
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
priority=10
EOF
}

main
