#!/bin/bash

# Server Settings: General
USE_OPENSTARBOUND=${USE_OPENSTARBOUND:-false}
SERVER_NAME=${SERVER_NAME} # defaults to Plains of Pain Server
SERVER_PORT=${SERVER_PORT} # defaults to 7777
SERVER_QUERYPORT=${SERVER_QUERYPORT} # defaults to 27016

# Server Settings: Authentication
## RCON password - must use Docker secret 'starbound_rcon_password'
SERVER_RCON_PASSWORD=""
if [ -f /run/secrets/starbound_rcon_password ]; then
  SERVER_RCON_PASSWORD=$(cat /run/secrets/starbound_rcon_password)
  if [ -n "$SERVER_RCON_PASSWORD" ]; then
    info "Using Starbound RCON password from Docker secrets"
  else
    info "Starbound RCON password secret file exists - but is empty"
  fi
else
  info "No Starbound RCON password secret found"
fi

# Steam Settings
GAME_BRANCH=${GAME_BRANCH:-public}
STEAMCMD_ARGS=${STEAMCMD_ARGS:-"$GAME_BRANCH" validate}

# Update
UPDATE_CRON=${UPDATE_CRON:-}
UPDATE_CHECK_PLAYERS=${UPDATE_CHECK_PLAYERS:-false}

# Backup
BACKUP_CRON=${BACKUP_CRON:-}
BACKUP_DIR=${BACKUP_DIR:-backups}
BACKUP_MAX_COUNT=${BACKUP_MAX_COUNT:-0}

# Hooks
BOOTSTRAP_HOOK=${BOOTSTRAP_HOOK:-}
UPDATE_PRE_HOOK=${UPDATE_PRE_HOOK:-}
UPDATE_POST_HOOK=${UPDATE_POST_HOOK:-}
BACKUP_PRE_HOOK=${BACKUP_PRE_HOOK:-}
BACKUP_POST_HOOK=${BACKUP_POST_HOOK:-}

# Docker process user/group IDs
PUID=${PUID:-4711}
PGID=${PGID:-4711}


