#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/openstarbound-updater-shared"

main() {
  info "Running openstarbound-updater"
  updateOpenStarbound
  info "openstarbound-updater complete"
}

main