#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/openstarbound-updater-shared"

main() {
  info "Running openstarbound-updater"
  
  # Skip if OpenStarbound is not enabled
  if [ "${USE_OPENSTARBOUND:-false}" != "true" ]; then
    debug "OpenStarbound is not enabled - exiting"
    exit 0
  fi
  
  updateOpenStarbound
  info "openstarbound-updater complete"
}

main
