#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/starbound-bootstrap-shared"

main() {
  info "Running starbound-bootstrap"
  prepareStarboundAppFolders
  updateOrCreateStarboundServerConfig
  prepareSteamA2sPythonLibrary
  bootstrapHook

  initCrontab

  # Ensure OpenStarbound (if enabled) is installed/updated after Starbound is installed/updated
  if [ "$USE_OPENSTARBOUND" == "true" ]; then
    supervisorctl start update-sequence:*
  else
    supervisorctl start starbound-updater
  fi
  info "Bootstrap complete"
}

main