name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
      - LICENSE
      - docker-compose.yml
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: CI-${{ github.ref }}

jobs:
  release:
    name: Build docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Login to Github Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub registry
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:dev-osb
            ${{ vars.DOCKER_HUB_USERNAME }}/openstarbound-server:dev-osb
